run:
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: github.com/aweris/demo-devconf-cz-2024
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  enable:
    - goimports
    - misspell
    - nolintlint
    - revive