name: CI

on:
  push:
    branches: [main]
  pull_request: {}

env:
  DAGGER_VERSION: "0.11.6"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Run pipeline
        uses: dagger/dagger-for-github@158efd19b6af5ff000289d6c7c507ada3c7b3b9b # v5.8.0
        with:
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} build
          version: ${{ env.DAGGER_VERSION }}

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Run pipeline
        uses: dagger/dagger-for-github@158efd19b6af5ff000289d6c7c507ada3c7b3b9b # v5.8.0
        with:
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} test
          version: ${{ env.DAGGER_VERSION }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Run pipeline
        uses: dagger/dagger-for-github@158efd19b6af5ff000289d6c7c507ada3c7b3b9b # v5.8.0
        with:
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} lint
          version: ${{ env.DAGGER_VERSION }}
